name: "setup-pandoc"
description: "Composite action to setup pandoc."

inputs:
  pandoc-version:
    required: false
    description: "The pandoc version to use"
    default: "3.2.1"

runs:
  using: "composite"
  steps:
    - name: Load cached Pandoc
      id: cached-pandoc
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/pandoc
        key: pandoc-${{ runner.os }}-${{ hashFiles('.tool-versions') }}

    - name: Install
      uses: pandoc/actions/setup@v1
      with:
        version: ${{ inputs.pandoc-version }}

    - name: Run pandoc
      run: pandoc --version
      shell: bash
