name: "setup-pandoc"
description: "Composite action to setup pandoc."

inputs:
  pandoc-version:
    required: false
    description: "The pandoc version to use"
    default: "3.2.1"

runs:
  using: "composite"
  steps:
    - name: Load cached Pandoc
      id: cached-pandoc
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/pandoc
        key: pandoc-${{ runner.os }}-${{ hashFiles('.tool-versions') }}

    - name: Install Pandoc
      if: steps.cached-pandoc.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc=${{ inputs.python-version }}
      shell: bash
